version: "3.8" # Versão moderna
services:
  client:
    image: "trogistdev/multi-client"
    deploy:
      resources:
        limits:
          memory: 128M
  api:
    image: "trogistdev/multi-server"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "trogistdev/multi-worker"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "trogistdev/multi-nginx"
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "80:80" # O Beanstalk vai ligar o tráfego externo aqui
    depends_on:
      - client
      - api