name: CI Multi-Container
on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Build das imagens de TESTE (Geralmente apenas do Client)
      - name: Build Test Image
        run: docker build -t trogist/react-test -f ./client/Dockerfile.dev ./client

      - name: Run Tests
        run: docker run -e CI=true trogist/react-test npm test

      # 2. Login no Docker Hub 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build e Push de TODAS as imagens de produção
      - name: Build and Push Multi-Images
        run: |
          docker build -t trogistdev/multi-client ./client
          docker build -t trogistdev/multi-server ./server
          docker build -t trogistdev/multi-worker ./worker
          docker build -t trogistdev/multi-nginx ./nginx
          
          docker push trogistdev/multi-client
          docker push trogistdev/multi-server
          docker push trogistdev/multi-worker
          docker push trogistdev/multi-nginx